sudo: no
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
      - cabal-install
      - liblua5.2-dev
      - lua5.2
      - nodejs
install:
  - cabal update
  - cabal install shellcheck
  - npm install eclint
before_script:
  - eclint .
  - shellcheck *.sh
script:
  - ./build-linux.sh
  - build-linux/shellprompt version
