sudo: no
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
      - liblua5.2-dev
      - lua5.2
      - nodejs
install:
  - npm install eclint
  - git clone https://github.com/davidm/lua-inspect.git
before_script:
  - eclint .
  - lua-inspect/luainspect -fdelimited *.lua
script:
  - ./build-linux.sh
after_script:
  - build-linux/shellprompt version
