extern int shellprompt_os_is_superuser(lua_State *L);
extern int shellprompt_os_get_username(lua_State *L);
extern int shellprompt_os_get_full_hostname(lua_State *L);
extern int shellprompt_os_get_cur_directory(lua_State *L);
extern int shellprompt_os_ensure_dir_exists(lua_State *L);
extern int shellprompt_os_get_output(lua_State *L);
extern int shellprompt_os_unamesys(lua_State *L);
extern int shellprompt_os_termcolsrows(lua_State *L);
extern void shellprompt_os_register(lua_State *L);
